name       : haskell-pid1
version    : 0.1.2.0
release    : 3
source     :
    - http://hackage.haskell.org/package/pid1-0.1.2.0/pid1-0.1.2.0.tar.gz : 9e97bf9b4b6ffd6a9b706cc6d5fadd8089cd37d2b8763111bd743104db267f76
license    : MIT
component  : programming.haskell
summary    : Do signal handling and orphan reaping for Unix PID1 init processes.
description: |
    Do signal handling and orphan reaping for Unix PID1 init processes.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
