name       : haskell-pid1
version    : 0.1.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/pid1-0.1.0.1/pid1-0.1.0.1.tar.gz : 163b6dc85426558ad1a897675bf7f560389addf172c8e5858f817342ee7345c8
license    : MIT
component  : programming.haskell
summary    : Do signal handling and orphan reaping for Unix PID1 init processes.
description: |
    Do signal handling and orphan reaping for Unix PID1 init processes.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
